#if !defined(AFX_MOADDRESSLOCATION_H__F3577752_ACA0_4D51_B4AB_59CA682B0D05__INCLUDED_)
#define AFX_MOADDRESSLOCATION_H__F3577752_ACA0_4D51_B4AB_59CA682B0D05__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoPoint;

/////////////////////////////////////////////////////////////////////////////
// CMoAddressLocation wrapper class

class CMoAddressLocation : public COleDispatchDriver
{
public:
	CMoAddressLocation() {}		// Calls COleDispatchDriver default constructor
	CMoAddressLocation(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoAddressLocation(const CMoAddressLocation& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CMoPoint GetLocation();
	void SetLocation(LPDISPATCH);
	short GetMatchScore();
	void SetMatchScore(short);
	long GetStreetSide();
	void SetStreetSide(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOADDRESSLOCATION_H__F3577752_ACA0_4D51_B4AB_59CA682B0D05__INCLUDED_)
