#if !defined(AFX_MOFIELD_H__1BC26A5B_3B1B_4E2D_822E_933DAAA40B8B__INCLUDED_)
#define AFX_MOFIELD_H__1BC26A5B_3B1B_4E2D_822E_933DAAA40B8B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMoField wrapper class

class CMoField : public COleDispatchDriver
{
public:
	CMoField() {}		// Calls COleDispatchDriver default constructor
	CMoField(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoField(const CMoField& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetName();
	void SetName(LPCTSTR);
	long GetType();
	void SetType(long);
	CString GetValueAsString();
	void SetValueAsString(LPCTSTR);
	VARIANT GetValue();
	void SetValue(const VARIANT&);
	VARIANT Get_Value();
	void Set_Value(const VARIANT&);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOFIELD_H__1BC26A5B_3B1B_4E2D_822E_933DAAA40B8B__INCLUDED_)
