#if !defined(AFX_MOPROJCOORDSYS_H__DC541253_1B5E_4D3F_8709_33A3E3D37C8F__INCLUDED_)
#define AFX_MOPROJCOORDSYS_H__DC541253_1B5E_4D3F_8709_33A3E3D37C8F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CMoGeoCoordSys;
class CMoUnit;
class CMoProjection;

/////////////////////////////////////////////////////////////////////////////
// CMoProjCoordSys wrapper class

class CMoProjCoordSys : public COleDispatchDriver
{
public:
	CMoProjCoordSys() {}		// Calls COleDispatchDriver default constructor
	CMoProjCoordSys(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoProjCoordSys(const CMoProjCoordSys& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetType();
	void SetType(long);
	CString GetName();
	void SetName(LPCTSTR);
	CMoGeoCoordSys GetGeoCoordSys();
	void SetGeoCoordSys(LPDISPATCH);
	CMoUnit GetUnit();
	void SetUnit(LPDISPATCH);
	CMoProjection GetProjection();
	void SetProjection(LPDISPATCH);
	BOOL GetIsProjected();
	void SetIsProjected(BOOL);

// Operations
public:
	void SetParameter(long ParameterType, double ParameterValue);
	double GetParameter(long ParameterType);
	LPDISPATCH Transform(LPDISPATCH FromCoordSys, LPDISPATCH FromShape, const VARIANT& DensificationTolerance, const VARIANT& GeoTransformation);
	void Export(LPCTSTR OutName);
	CString ReturnDescription();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOPROJCOORDSYS_H__DC541253_1B5E_4D3F_8709_33A3E3D37C8F__INCLUDED_)
