//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GraduDeMIS.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_Sub_FORMVIEW                101
#define IDD_GRADUDEMIS_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDR_MENU                        129
#define IDD_STU_DIALOG                  130
#define IDD_STU_DIALOG1                 131
#define IDD_STU_DIALOG2                 136
#define IDB_BITMAP1                     145
#define IDB_BITMAP2                     147
#define IDD_TEACHER_DIALOG1             148
#define IDD_TEACHER_DIALOG2             149
#define IDD_TEACHER_DIALOG              150
#define IDD_StuCoi_SubDLG               151
#define IDD_SubDLG                      151
#define IDD_StuCoi_InfoDLG              152
#define IDD_LOGIN_DLG                   153
#define IDD_SubInfoDLG                  154
#define IDC_CURSOR1                     155
#define IDD_Tecr_DclrSubDlg             156
#define IDD_StuInfo_DLG                 158
#define IDD_TecrInfo_DLG                159
#define IDB_BITMAP3                     161
#define IDD_SysLog_DLG                  162
#define IDD_UserGL                      163
#define IDB_BITMAP4                     164
#define IDB_BITMAP5                     166
#define IDD_AnswZigeChek_DLG            168
#define IDD_ThesisGroup_DLG             169
#define IDD_DocChek_DLG                 170
#define IDD_ChoiStatusShow_DLG          171
#define IDD_SubQuery_DLG                172
#define IDD_SubOper_DLG                 173
#define IDD_DclrSubStatus_DLG           174
#define IDD_DabianFenzu_DLG             176
#define IDD_Subject_DLG                 177
#define IDD_SubTab1_DLG                 178
#define IDD_SubTab2_DLG                 179
#define ICON_PREVIEW                    182
#define IDD_Kaoqin_DLG                  183
#define DLG_SYS_PREVIEW                 220
#define DLG_SYS_PREPARENT               227
#define DLG_SYS_PREGOTO                 228
#define BTN_OK                          1002
#define BTN_CANCEL                      1003
#define BMP_BACK                        1004
#define IDC_EDIT1                       1006
#define IDC_STUTAB1_EDIT                1006
#define IDC_EDIT_ID                     1006
#define IDC_TEACHER_EDIT                1006
#define IDC_TECR_ID                     1006
#define IDC_QuerySubEDIT                1006
#define IDC_USER                        1006
#define IDC_SubTitle_EDIT               1006
#define IDC_ChoiSubStatus_EDIT          1006
#define IDC_EDIT                        1006
#define IDC_EDIT_Kaiti                  1006
#define IDC_ForLanLevel_EDIT            1006
#define IDC_EDIT_UnAttRea               1006
#define IDC_EDIT_Demand                 1006
#define IDC_EDIT_NAME                   1007
#define IDC_TECR_NAME                   1007
#define IDC_PASSWORD                    1007
#define IDC_Exit_BTN                    1007
#define IDC_EDIT_CompuLevel             1007
#define IDC_EDIT_Shixi                  1007
#define IDC_ComLevel_EDIT               1007
#define IDC_SUB_PRO                     1007
#define IDC_EDIT_SEX                    1008
#define IDC_TECR_SEX                    1008
#define IDC_DEL                         1008
#define IDC_EDIT_EngLevel               1008
#define IDC_EDIT_Fanyi                  1008
#define IDC_SchShip_EDIT                1008
#define IDC_SUB_DEMAND                  1008
#define IDC_EDIT_AGE                    1009
#define IDC_TECR_AGE                    1009
#define IDC_EDIT_ColiResult             1009
#define IDC_EDIT_CLASS                  1010
#define IDC_TECR_TRROOM                 1010
#define IDC_User_LIST                   1010
#define IDC_TAB1                        1011
#define IDC_EDIT_DEPART                 1011
#define IDC_TECR_LEVEL                  1011
#define IDC_USER1                       1011
#define IDC_Passwd                      1012
#define IDC_TECR_Ascio                  1012
#define IDC_LIST1                       1013
#define IDC_RePass                      1013
#define IDC_STUTAB1_COMBO               1014
#define IDC_ADD                         1014
#define IDC_STUTAB1_BUTTON              1015
#define IDC_STUTAB1_COMBO2              1016
#define IDC_BUTTON_ADD                  1017
#define IDC_BUTTON_EDIT                 1018
#define IDC_TEACHER_TAB                 1018
#define EDT_GOTO                        1018
#define IDC_BUTTON_DEL                  1019
#define IDC_TEACHER_LIST                1019
#define IDC_BUTTON_SAVE                 1020
#define IDC_TEACHER_COMBO               1020
#define IDC_BUTTON_CANCLE               1021
#define IDC_TEACHER_BTN                 1021
#define IDC_PRINTTEST                   1022
#define IDC_TECR_ADD                    1023
#define IDC_TECR_EDIT                   1024
#define IDC_MyInfo_BTN                  1024
#define IDC_TECR_DEL                    1025
#define IDC_ChoiSub_LIST                1025
#define IDC_TECR_SAVE                   1026
#define IDC_SubQuery_LIST               1026
#define IDC_DclrSub_BTN                 1026
#define IDC_TECR_CANCEL                 1027
#define IDC_StuInfo_BTN                 1027
#define IDC_DclrSub_BTN2                1027
#define IDC_ChoiStu_BTN                 1027
#define IDC_SubQuery_COMBO              1028
#define IDC_TecrInfo_BTN                1028
#define IDC_QUERY_BTN                   1029
#define IDC_STU_RADIO                   1030
#define IDC_Add_BTN                     1030
#define IDC_TECR_RADIO                  1031
#define IDC_SubType_COMBO               1033
#define IDC_SubProEDIT                  1034
#define IDC_SubDemand_EDIT              1035
#define IDC_TecrAsoci_EDIT              1036
#define IDC_EditPswd_BTN                1037
#define IDC_TecrAsoci_EDIT2             1037
#define IDC_FormerPswd_EDIT             1038
#define IDC_NewPswd_EDIT                1039
#define IDC_EnsuPswd_EDIT               1040
#define IDC_CancelBTN                   1041
#define IDC_OkBTN                       1042
#define IDC_QueChoiedSub_BTN            1043
#define IDC_ToChoiSub_BTN               1044
#define IDC_STATIC1                     1045
#define IDC_STATIC2                     1046
#define IDC_STATIC3                     1047
#define IDC_STATIC4                     1048
#define IDC_EDIT_AttDays                1050
#define IDC_EDIT_HoliDays               1051
#define IDC_EDIT_YDaoDays               1052
#define IDC_EDIT_Result                 1053
#define IDC_StuID_COMBO                 1054
#define IDC_StuName_COMBO               1055
#define IDC_Class_COMBO2                1056
#define IDC_COMBO_Kaiti                 1057
#define IDC_CHECK2                      1058
#define IDC_KT_bPlan_CHECK              1058
#define IDC_CHECK3                      1059
#define IDC_KT_bBaseCndi_CHECK          1059
#define IDC_CHECK4                      1060
#define IDC_Sex_COMBO                   1060
#define IDC_FY_bNum_CHECK               1060
#define IDC_COMBO_Fanyi                 1061
#define IDC_Age_COMBO                   1061
#define IDC_CHECK5                      1062
#define IDC_STATIC_ChoiStatus           1062
#define IDC_FY_bRelate_CHECK            1062
#define IDC_COMBO_Shixi                 1063
#define IDC_BUTTON1                     1063
#define IDC_SeeChoisubInfo_BTN          1063
#define IDC_Ok_BTN                      1063
#define IDC_CHECK6                      1064
#define IDC_BUTTON2                     1064
#define IDC_EnterChoiSub_BTN            1064
#define IDC_SubKind_COMBO               1064
#define IDC_SX_bRelate_CHECK            1064
#define IDC_CHECK7                      1065
#define IDC_DclrMaxNum_STATIC           1065
#define IDC_KT_bSubmit_CHECK            1065
#define IDC_CHECK8                      1066
#define IDC_DclrNum_STATIC              1066
#define IDC_FY_bSubmit_CHECK            1066
#define IDC_CHECK9                      1067
#define IDC_SX_bSubmit_CHECK            1067
#define IDC_ChoisubStu_LIST             1069
#define IDC_Ownsub_LIST                 1071
#define IDC_COMBO1                      1076
#define IDC_COMBO2                      1077
#define IDC_SUB_TEA                     1077
#define IDC_COMBO3                      1078
#define IDC_Depart_COMBO                1078
#define IDC_STATIC_Position             1081
#define IDC_User_COMBO                  1082
#define IDC_STATIC_Date                 1082
#define IDC_DATETIMEPICKER1             1082
#define IDC_LoginBtn                    1083
#define IDC_LIST                        1083
#define IDC_SUB_NAME                    1083
#define IDC_ExitBtn                     1084
#define IDC_SUB_TYPE                    1084
#define IDC_UserType_COMBO              1085
#define IDC_UserUnit_COMBO              1086
#define IDC_Save_BTN                    1086
#define IDC_STATIC_Expers               1086
#define IDC_Cancel_BTN                  1087
#define IDC_Class_COMBO                 1087
#define IDC_IsAdmin_CHECK               1088
#define IDC_Name_COMBO                  1088
#define IDC_StuName_COMBO2              1088
#define IDC_DabianType_COMBO            1089
#define IDC_DATETIMEPICKER_From         1089
#define IDC_DATETIMEPICKER_To           1090
#define IDC_DATETIMEPICKER_Date         1091
#define IDC_CHECK1                      1094
#define IDR_TOOLBAR                     1113
#define IDC_SUP                         1115
#define IDC_SDOWN                       1116
#define SPIN_GOTO                       1117
#define ID_MENUITEM32772                32772
#define ID_MENUITEM32773                32773
#define ID_MENUITEM32775                32775
#define ID_ExitSys                      32777
#define ID_MENUITEM32778                32778
#define ID_MENUITEMUserHelp             32778
#define IDD_Choisublist_DLG             32779
#define ID_MENUITEM32781                32781
#define ID_MENUITEM32782                32782
#define ID_MENUITEM32783                32783
#define ID_MENUITEM_DocChek             32783
#define ID_MENUITEM32784                32784
#define ID_MENUITEM32785                32785
#define ID_MENUITEM32786                32786
#define ID_MENUITEM32787                32787
#define ID_MENUITEM32788                32788
#define ID_MENUITEM_DBCopy              32789
#define ID_MENUITEM_DBRestore           32790
#define TBTN_TOP                        32811
#define TBTN_PREVIOUS                   32812
#define TBTN_GOTO                       32814
#define TBTN_NEXT                       32815
#define TBTN_LAST                       32816
#define TBTN_EXIT                       32818
#define TBTN_PRINT                      32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
