//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HCDB.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDF_MBP                         101
#define IDD_FORMVIEW1                   102
#define IDR_MAINFRAME                   128
#define IDR_HCDBTYPE                    129
#define IDB_IMAGELIST                   129
#define IDD_MQQAPPEARANCE_DIALOG        130
#define IDB_SMALL_IMAGELIST             130
#define IDC_CURSOR1                     131
#define IDD_FOREMANGE                   131
#define IDC_DRAGGING                    132
#define IDF_IN_STOCKMANGE               132
#define IDC_NODRAGGING                  133
#define IDF_INSTOCKQUERY                133
#define IDC_HANDCUR                     134
#define IDF_INDETAIL                    134
#define IDF_OUTDETAIL                   135
#define IDF_OUT_STOCKMANGE              136
#define IDF_GATHER_OUT                  137
#define IDB_BITMAP1                     137
#define IDF_GATHER_IN                   138
#define IDF_OUTSTOCKQUERY               139
#define IDD_BACKUPDIALOG                140
#define IDD_RESTOREDIALOG               141
#define IDD_SALESQUIT                   142
#define IDD_XStabdlg6                   146
#define IDD_PROVDIALOG                  147
#define IDD_SYSDLG                      151
#define IDD_STOCKMANAGEDIALOG           156
#define IDD_DIALOG1                     160
#define IDD_SALESQUERY                  230
#define IDD_XStabdlg4                   231
#define IDD_SALESMANAGE                 232
#define IDC_LIST1                       1000
#define IDC_EDIT1                       1001
#define IDC_MERCID                      1001
#define IDC_EDIT_INNUMBER               1001
#define ID_CSlist                       1001
#define IDC_EDIT2                       1002
#define IDC_MERCNUM                     1002
#define IDC_EDITPROVNAME                1002
#define ID_CSlist2                      1002
#define IDC_EDIT3                       1003
#define IDC_SINGLEDISCOUNT              1003
#define ID_CSlist3                      1003
#define IDC_ALLMONEY                    1004
#define IDC_ADDUSER                     1004
#define IDC_REALLMONEY                  1005
#define IDC_DELUSER                     1005
#define IDC_BACKMONEY                   1006
#define IDC_MODIPASS                    1006
#define IDC_BUYNUM                      1007
#define IDC_BTN_SINREBATE               1008
#define IDC_EDITNAME                    1008
#define IDC_EDITPASS                    1009
#define IDC_BTN_BUYREBATE               1010
#define IDC_EDITPASSR                   1010
#define IDC_BTNOK                       1011
#define IDC_BTN_DEL                     1013
#define IDC_BTN_DELMERC                 1013
#define IDC_BUTTON4                     1014
#define IDC_BTN_LOCKSCREEN              1014
#define IDC_BTN_OK                      1014
#define IDC_BUTTON5                     1015
#define IDC_BTNCANCELSALES              1015
#define IDC_BTN_CANCEL                  1015
#define IDC_BUTTON6                     1016
#define IDC_LIST                        1016
#define IDC_BUTTON7                     1017
#define IDC_BUTTON8                     1018
#define IDC_BTNQUIT                     1018
#define IDC_EDIT_REALMONEY              1021
#define IDC_ANOTHER                     1022
#define IDC_EDIT_REALMONEY2             1023
#define IDC_TAB1                        1024
#define IDC_EDITOLDPASS                 1024
#define IDC_EDITNEWPASS                 1026
#define IDC_EDITNEWPASSR                1027
#define IDC_BUTTON1                     1029
#define IDC_BUTTON2                     1030
#define IDC_BTN_ADDNEW                  1030
#define IDC_TN_SAVE                     1032
#define IDC_BUTTON_PRINT                1033
#define IDC_DATETIMEPICKER1             1035
#define IDC_COMBO1                      1036
#define IDC_COMBOINTYPE                 1036
#define IDC_COMBO2                      1037
#define IDC_COMBOPROVID                 1037
#define IDC_EDIT4                       1038
#define IDC_LIST2                       1039
#define IDC_EDIT5                       1040
#define IDC_EDIT6                       1041
#define IDC_EDIT7                       1042
#define IDC_COMBO_SPTYPE                1042
#define IDC_EDIT8                       1043
#define IDC_EDIT_NAME                   1043
#define IDC_EDIT9                       1044
#define IDC_EDIT10                      1045
#define IDC_STATIC1                     1046
#define IDC_STATIC2                     1047
#define IDC_BTN_QUERY                   1047
#define IDC_STATIC3                     1048
#define IDC_BTN_SET                     1048
#define IDC_STATIC4                     1049
#define IDC_STATIC5                     1050
#define IDC_STATIC6                     1051
#define IDC_STATIC7                     1052
#define IDC_STATIC8                     1053
#define IDC_STATIC9                     1054
#define IDC_COMBO3                      1055
#define IDC_STATIC10                    1056
#define IDC_HOTKEY1                     1057
#define IDC_CHECK1                      1058
#define IDC_CHECK2                      1059
#define IDC_DATETIMEPICKER2             1060
#define IDC_BUTTON3                     1061
#define IDC_EDIT11                      1063
#define IDC_STATIC20                    1064
#define IDC_STATIC21                    1065
#define IDC_STATIC22                    1066
#define IDC_STATIC23                    1067
#define ID_INFO                         1075
#define ID_xsdID                        1079
#define ID_jbrID                        1080
#define IDC_SHUAXIN                     1081
#define ID_MERCID                       1082
#define ID_QUITNUM                      1083
#define ID_OK                           1085
#define IDC_EDIT_MIN                    1086
#define IDC_EDIT_MAX                    1087
#define ID_BACKMONEY                    1087
#define ID_TSPRD                        1089
#define IDC_BTN_CLOSE                   1089
#define ID_TSPCD                        1090
#define IDC_find                        1091
#define IDC_BUTTON_SHOWSPECIAL          1091
#define ID_riqi                         1092
#define ID_LIST1                        1092
#define ID_LIST2                        1093
#define IDC_CHAXUNxsd                   1094
#define ID_LIST3                        1094
#define IDC_SETTIME                     1095
#define ID_OPERID                       1095
#define IDC_SHOWALL                     1096
#define ID_BUYID                        1096
#define IDC_INVALIDATE                  1097
#define IDC_DATETIMEPICKER4             1098
#define IDC_SEPARATOR                   1098
#define IDC_jiesuan                     1099
#define IDC_XSmoney                     1100
#define IDC_THmoney                     1101
#define IDC_JXSmoney                    1102
#define IDM_FOREMANGE                   32771
#define IDM_IN_STOCKMANGE               32772
#define IDM_INSTOCKQUERY                32773
#define IDM_INDETAIL                    32774
#define IDM_OUTDETAIL                   32775
#define IDM_OUT_STOCKMANGE              32776
#define IDM_OUTSTOCKQUERY               32777
#define IDM_GETHER_IN                   32778
#define IDM_GETHER_OUT                  32779
#define IDF_BACKUP                      32780
#define IDF_RESTORE                     32781
#define IDM_MAIN                        32782
#define IDF_SALESQUIT                   32783
#define IDF_SALEQUERY                   32784
#define ID_USERMANAGE                   32785
#define ID_GFX_SMALLICON                50000
#define ID_GFX_LARGEICON                50001
#define ID_GFX_REMOVEITEM               50002
#define ID_GFX_RENAMEITEM               50003
#define ID_GFX_GROUPICON                50004
#define ID_GFX_FONTCICON                50005
#define ID_GFX_BACKCICON                50006
#define IDC_STRING1                     61446
#define IDC_STRING2                     61447
#define IDC_STRING3                     61448
#define IDC_STRING4                     61449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
