//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MTAS.rc
//
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_MTASTYPE                    129
#define IDB_TREE_CLOSED                 129
#define IDB_BITMAP1                     130
#define IDD_PROPERTIES                  131
#define IDB_CODE_PROJECT                131
#define IDI_CODE_PROJECT                132
#define IDC_CURSORMOVE                  133
#define IDD_COURSEWARE_PREVIEW          133
#define IDR_MYLIST_MENU                 134
#define IDR_MY_MENU                     134
#define IDR_LIST_CTRL_MENU              134
#define IDI_STOP                        137
#define IDI_PLAY                        138
#define IDI_PAUSE                       139
#define IDI_WORD                        140
#define IDI_FLASH                       141
#define IDI_PPT                         142
#define IDR_FLASH_TOOLBAR               143
#define IDI_ZOOM_IN                     145
#define IDI_ZOOM_OUT                    146
#define IDI_NORMAL_SCREEN               147
#define IDI_FULL_SCREEN                 148
#define IDB_NORMAL_SCREEN               149
#define IDB_FLASH_PAUSE                 150
#define IDB_FLASH_PLAY                  151
#define IDB_FLASH_STOP                  152
#define IDR_TREE_MENU                   152
#define IDB_FULL_SCREEN                 153
#define IDI_FLASH_FILE                  158
#define IDI_PPT_FILE                    159
#define IDI_WORD_FILE                   160
#define IDI_COMMUNICATION               161
#define IDI_ASSIGNMENT                  162
#define IDI_SLIDER                      163
#define IDI_MOVIE                       164
#define IDI_NAVIGATE_STOP               170
#define IDI_NAVIGATE_BACKWARD           171
#define IDI_NAVIGATE_FORWARD            172
#define IDI_NAVIGATE_REFRESH            173
#define IDR_NAVIGATE_TOOLBAR            174
#define IDI_NAVIGATE_GOTO               176
#define IDR_CW_TOOLBAR                  177
#define IDI_CW_DEL                      179
#define IDI_CW_ADD                      180
#define IDI_CW_OPEN                     181
#define IDI_CW_DIR                      182
#define IDI_HELP                        183
#define IDD_OPTIONS                     184
#define IDD_ADD_CWI_DIALOG              185
#define IDD_ADD_CLASS_DIALOG            188
#define IDI_CANCEL                      190
#define IDI_OK                          191
#define IDI_UP                          192
#define IDI_DOWN                        193
#define IDI_ADD                         194
#define IDI_RESET                       196
#define IDI_BROWSE                      197
#define IDD_ADD_CHAPTER_DIALOG          198
#define IDD_ADD_SECTION_DIALOG          199
#define IDD_ADD_COURSEWARE_DIALOG2      200
#define IDB_BITMAP2                     201
#define IDB_BITMAP3                     202
#define IDD_ADD_COURSEWARE_DIALOG       202
#define IDB_BITMAP4                     203
#define IDB_BACKGROUND                  204
#define IDR_WAVE                        204
#define IDB_TREE_OPENED                 205
#define IDB_CLOCKST_SMALL               206
#define IDB_CLOCKST_BIG                 207
#define IDB_CLOCKST_PANE                208
#define IDD_CLOCK_DIALOG                209
#define IDR_CLOCK_MENU                  210
#define IDD_ADD_COURSEWARE_DIALOG3      212
#define IDD_ADD_CHAPTER_DIALOG2         213
#define IDD_ADD_SECTION_DIALOG2         214
#define IDI_SUB                         215
#define IDB_BITMAP_SPLASH               217
#define IDR_TOOLBAR_FOR_PPTLIST         219
#define IDR_TOOLBAR_FOR_FLASHLIST       221
#define IDR_TOOLBAR_FOR_WORDLIST        223
#define IDR_TOOLBAR_FOR_TREE_COURSEWARE 225
#define IDR_TOOLBAR_FOR_TREE_SECTION    227
#define IDR_TOOLBAR_FOR_TREE_CHAPTER    229
#define IDR_TOOLBAR_FOR_TREE_CLASS      231
#define IDR_TOOLBAR_FOR_TREE_CONTEXT    233
#define IDR_TOOLBAR_FOR_TAB_FRAME       235
#define IDI_CW_ADDS                     237
#define IDR_POPUP_OUTLOOKTABCTRL        400
#define IDD_OUTLOOK_CMD                 500
#define IDD_OUTLOOK_CMD_BUTTON_UP       501
#define IDD_OUTLOOK_CMD_BUTTON_DOWN     502
#define IDD_OUTLOOK_CMD_BUTTON_RESET    503
#define IDD_OUTLOOK_CMD_LIST1           504
#define IDC_LABELED                     1000
#define IDC_URLED                       1001
#define IDC_TOOLTIPED                   1002
#define IDC_BK_BITMAP                   1002
#define IDC_EDIT_PATH                   1002
#define IDC_BK_GRADIENT                 1003
#define IDC_BROWSE                      1003
#define IDC_BK_NORMAL                   1004
#define IDC_COMBO_CLASS                 1004
#define IDC_TILED                       1005
#define IDC_COMBO_CHAPTER               1005
#define IDC_HORIZ                       1006
#define IDC_COMBO_SECTION               1006
#define IDADD                           1007
#define IDC_EDIT_NAME                   1008
#define IDC_EDIT_TYPE                   1009
#define IDC_EDIT_CLASS_NAME             1010
#define IDC_EDIT_CLASS                  1012
#define IDC_EDIT_CHAPTER                1013
#define IDC_STATIC_EMAIL                1013
#define IDC_EDIT_SECTION                1014
#define IDC_EDIT_SIZE                   1018
#define IDC_EDIT_MODTIME                1019
#define IDC_EXPLORER                    1020
#define IDC_CLOCKFRAME                  1021
#define IDC_BUTTON_BROWSE               1026
#define IDC_BUTTON_DELETE               1029
#define ID_DUMMY                        1033
#define ID_POPUP_OUTLOOKTABCTRL_POP     32000
#define ID_POPUP_OUTLOOKTABCTRL_PUSH    32001
#define ID_POPUP_OUTLOOKTABCTRL_MANAGE  32002
#define IDR_ADD_PPT                     32771
#define IDR_DEL_PPT                     32772
#define IDR_OPEN_PPT                    32773
#define ID_SECTION_REMOVE               32773
#define IDR_OPEN_FLASH                  32774
#define IDR_DEL_FLASH                   32775
#define ID_FILE_PRINTALLSECTIONS        32775
#define IDR_OPEN_WORD                   32776
#define IDR_ADD_WORD                    32777
#define IDR_DEL_WORD                    32778
#define IDR_ADD_FLASH                   32779
#define ID_ADD_FLASH                    32780
#define ID_MANAGE_SLIDES                32781
#define ID_DEL_FLASH                    32783
#define ID_DEL_COURSEWARE               32783
#define ID_SUSPEND_FLASH                32784
#define ID_PLAY_FLASH                   32785
#define ID_PAUSE_FLASH                  32786
#define ID_STOP_FLASH                   32787
#define ID_ADD_PART                     32788
#define ID_ADD_SECTION                  32788
#define ID_DEL_CHAPTER                  32789
#define ID_FULL_SCREEN                  32790
#define ID_DEL_PART                     32790
#define ID_DEL_SECTION                  32790
#define ID_NORMAL_SCREEN                32791
#define ID_ADD_CHAPTER                  32791
#define IDC_FLASH_COMBOBOX              32792
#define ID_NAVIGATE_FORWARD             32793
#define ID_NAVIGATE_BACKWARD            32794
#define ID_NAVIGATE_STOP                32795
#define ID_NAVIGATE_REFRESH             32796
#define ID_NAVIGATE_TEXT                32797
#define IDC_NAVIGATE_COMBOBOX           32798
#define ID_ADDRESS_COMBOBOX             32801
#define ID_NAVIGATE_GOTO                32802
#define ID_PLAY_SLIDER                  32802
#define ID_VIEW_TOOLBAR_GUIDE           32803
#define ID_VIEW_TOOLBAR_FLASH           32804
#define ID_VIEW_COURSEWARE_GUIDE        32805
#define ID_VIEW_COURSEWARE_PREVIEW      32806
#define ID_OPEN_MYCOMPUTER              32808
#define ID_OPEN_MYDOCUMENT              32810
#define ID_OPEN_CW                      32812
#define ID_ADD_CW                       32813
#define ID_DEL_CW                       32814
#define ID_OPEN_CW_DIR                  32815
#define IDR_DIR_PPT                     32816
#define IDR_DIR_FLASH                   32817
#define IDR_DIR_WORD                    32818
#define ID_VIEW_COURSEWARE_ASSORT       32819
#define ID_VIEW_COURSE_GUIDE            32819
#define ID_ADD_CLASS                    32820
#define ID_DEL_CLASS                    32821
#define ID_ADD_COURSEWARE               32822
#define ID_OPEN_COURSEWARE              32823
#define ID_OPEN_COURSEWARE_DIR          32824
#define ID_VIEW_CLOCK                   32825
#define ID_CLOCK_CLOSE                  32826
#define ID_COURSE_ADD_CLASS             32828
#define ID_COURSE_ADD_CHAPTER           32829
#define ID_COURSE_ADD_SECTION           32830
#define ID_ADD_PPTS                     32832
#define ID_ADD_FLASHS                   32833
#define ID_ADD_WORDS                    32834
#define ID_ADD_MULTI_COURSEWARE         32835
#define ID_ADD_MULTI_CW                 32837
#define ID_VIEW_TOOLBAR_COURSEWARE      32838
#define ID_PAGE_ADD_BLANK               32839
#define ID_PAGE_CLOSE_CURRENT           32840
#define ID_PAGE_FIRST                   32841
#define ID_PAGE_PREVIOUS                32842
#define ID_PAGE_NEXT                    32843
#define ID_PAGE_LAST                    32844
#define ID_PAGE_PROPERTY                32845
#define IDR_ADD_WORDS                   32848
#define IDR_OPEN_WORD_DIR               32849

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
