//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HCOK.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HCOK_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     130
#define IDD_MANAGE                      131
#define IDD_MADDSONG                    132
#define IDD_SETPRICE                    133
#define IDD_DIALOG2                     134
#define IDD_DIALOG3                     135
#define IDD_MODIFISINGER                136
#define IDD_BYSINGER                    137
#define IDD_BYPINYIN                    138
#define IDD_BYZISHU                     139
#define IDD_BYSONGTYP                   140
#define IDD_SELECTED                    141
#define IDR_MENU                        142
#define IDD_DIALOG4                     143
#define DLG_SYS_PREVIEW                 220
#define ICON_PREVIEW                    221
#define DLG_SYS_PREPARENT               227
#define DLG_SYS_PREGOTO                 228
#define IDC_MEDIAPLAYER1                1000
#define IDC_BUTTON1                     1001
#define IDC_GPASSWOER                   1001
#define IDC_PREVIOUS                    1001
#define IDC_BUTTON2                     1002
#define IDC_NEXT                        1002
#define BTN_OK                          1002
#define IDC_SETROOM                     1002
#define IDC_USER                        1002
#define IDC_VOLUP                       1003
#define IDC_CUSTOMER                    1003
#define IDC_PRICE                       1003
#define BTN_CANCEL                      1003
#define IDC_OLDPASSWORD                 1003
#define IDC_VOLDOWN                     1004
#define IDC_CUSTOMER2                   1004
#define BMP_BACK                        1004
#define IDC_SETABATE                    1004
#define IDC_NEWPASSWORD                 1004
#define IDC_PLAYPAUSE                   1005
#define IDC_ADDSONG                     1005
#define IDC_STOP                        1006
#define IDC_DELSONG                     1006
#define IDC_DELLIST                     1007
#define IDC_SONGNAME                    1007
#define IDC_PLAYLIST                    1008
#define IDC_SINGER                      1008
#define IDC_SELECTED                    1008
#define IDC_SINFIND                     1009
#define IDC_FILENAME                    1009
#define IDC_PYFIND                      1010
#define IDC_FORMAT                      1010
#define IDC_NUFIND                      1011
#define IDC_COMBO1                      1011
#define IDC_TFIND                       1012
#define IDC_COMBO2                      1012
#define IDC_MANAGE                      1013
#define IDC_CHOOSE                      1013
#define IDC_CHECKOUT                    1014
#define IDC_ADD                         1014
#define IDC_LOGOUT                      1015
#define IDC_BUTTON16                    1016
#define IDC_ABATD                       1016
#define IDC_GIVENMONEY                  1016
#define IDC_QIUC                        1017
#define IDC_LIST1                       1017
#define IDC_QBACK                       1018
#define IDC_DEL                         1018
#define EDT_GOTO                        1018
#define IDC_CHECKINOUT                  1019
#define IDC_LIST2                       1020
#define IDC_ADDSINGER                   1021
#define IDC_SINGERSEX                   1023
#define IDC_MODIFSINGER                 1023
#define IDC_SGEAREA                     1024
#define IDC_RADIO1                      1024
#define IDC_SGEPIN                      1025
#define IDC_RADIO2                      1025
#define IDC_INFOR                       1026
#define IDC_EDIT1                       1027
#define IDC_SINER                       1028
#define IDC_RADIOdx                     1028
#define IDC_EDIT2                       1028
#define IDC_UP                          1029
#define IDC_EDIT3                       1029
#define IDC_DOWN                        1030
#define IDC_EDIT4                       1030
#define IDC_RADIOdb                     1031
#define IDC_EDIT5                       1031
#define IDC_RADIOlx                     1032
#define IDC_EDIT6                       1032
#define IDC_RADIOxb                     1033
#define IDC_EDIT7                       1033
#define IDC_EDIT8                       1034
#define IDC_SHOWTEXT                    1034
#define IDC_SET                         1036
#define IDC_HELP                        1037
#define IDC_OLDTEXT                     1039
#define IDC_NEWTEXT                     1040
#define IDC_MODIFY                      1041
#define IDC_SEPARATOR                   1042
#define IDR_TOOLBAR                     1113
#define IDC_SUP                         1115
#define IDC_SDOWN                       1116
#define SPIN_GOTO                       1117
#define ID_MENUNANQU                    32771
#define ID_MENUDANXUN                   32772
#define ID_MENUSHUBO                    32773
#define ID_MENUXUNBO                    32774
#define ID_MENUDELDAN                   32775
#define ID_MENUDELALL                   32776
#define ID_MENUITEMSEEFILE              32777
#define TBTN_TOP                        32811
#define TBTN_PREVIOUS                   32812
#define TBTN_GOTO                       32814
#define TBTN_NEXT                       32815
#define TBTN_LAST                       32816
#define TBTN_EXIT                       32818
#define TBTN_PRINT                      32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
