//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TBManager.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDD_FORMVIEW1                   102
#define IDR_MAINFRAME                   128
#define IDR_TBMANATYPE                  129
#define IDD_DIALOG1                     131
#define IDD_DIALOG2                     132
#define IDI_ICON1                       133
#define IDI_ICON2                       134
#define IDI_ICON3                       135
#define IDI_ICON4                       136
#define IDI_ICON5                       138
#define IDI_ICON6                       139
#define IDD_BACKUPDIALOG                140
#define IDI_ICON7                       141
#define IDD_RESTOREDIALOG               141
#define IDI_ICON8                       142
#define IDI_ICON9                       143
#define IDD_DIALOG_ADD                  144
#define IDD_DIALOG_TAB1                 145
#define IDD_DIALOG_TAB2                 146
#define IDD_DIALOG_TAB3                 147
#define IDD_DIALOG_TAB4                 148
#define IDI_ICON10                      149
#define IDD_DIALOG_RIGHT                150
#define IDD_DIALOG_LOGIN                151
#define IDB_BITMAP1                     154
#define IDB_BITMAP2                     155
#define IDB_BITMAP3                     156
#define IDB_BITMAP4                     157
#define IDB_BITMAP5                     158
#define IDB_BITMAP6                     159
#define IDB_BITMAP7                     160
#define IDB_BITMAP8                     161
#define IDB_BITMAP9                     162
#define IDB_BITMAP11                    164
#define IDD_DIALOG_HAND                 165
#define IDI_ICON11                      166
#define IDD_POWER                       167
#define IDC_LIST1                       1000
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_LIST2                       1002
#define IDC_DIFFICULTY                  1003
#define IDC_EDIT3                       1003
#define IDC_EDIT4                       1004
#define IDC_LIST3                       1004
#define IDC_BUTTON1                     1005
#define IDC_DIFFICULT2                  1005
#define IDC_EDIT5                       1005
#define IDC_LIST4                       1005
#define IDC_CHECK1                      1006
#define IDC_EDIT6                       1006
#define IDC_CHECK2                      1007
#define IDC_EDIT7                       1007
#define IDC_CHECK3                      1008
#define IDC_EDIT8                       1008
#define IDC_CHECK4                      1009
#define IDC_SCORE2                      1010
#define IDC_NNEWPASS                    1010
#define IDC_NUM3                        1011
#define IDC_DIFFICULT3                  1012
#define IDC_SCORE3                      1013
#define IDC_NUM4                        1014
#define IDC_DIFFICULT4                  1015
#define IDC_SCORE4                      1016
#define IDC_FULLDIFFICULT               1017
#define IDC_FULLSCORE                   1018
#define IDC_NUM1                        1019
#define IDC_NUM2                        1020
#define IDC_DIFFICULT1                  1021
#define IDC_SCORE1                      1022
#define IDC_EXAMNAME                    1023
#define IDC_BUTTON2                     1024
#define IDC_CONTENT                     1025
#define IDC_TREE1                       1026
#define IDC_TOP                         1027
#define IDC_BUTTON3                     1028
#define IDC_BUTTON4                     1029
#define ID_SELECT                       1029
#define IDC_LAST                        1030
#define IDC_BACK                        1031
#define IDC_FRONT                       1032
#define IDC_PAGENO                      1033
#define IDC_TAB1                        1034
#define IDC_UPDATE                      1035
#define IDC_RIGHT                       1036
#define IDC_COMBO1                      1037
#define IDC_NAME                        1038
#define IDC_COMBO2                      1038
#define IDC_PASSWORD                    1039
#define IDC_USERINFOMATION              1040
#define IDC_SHOWUPDATE                  1041
#define IDC_STATIC1                     1042
#define IDC_STATIC2                     1043
#define IDC_STATIC3                     1044
#define IDC_FSCORE1                     1045
#define IDC_ADDUSER                     1045
#define IDC_FSCORE2                     1046
#define IDC_FSCORE3                     1047
#define IDC_FSCORE4                     1048
#define IDC_PAGE                        1050
#define IDC_ADDTHEME                    1051
#define IDC_PAPERSNMAE                  1052
#define IDC_SUBJECTCONTENT              1053
#define ID_BACKUP                       1061
#define ID_RESTORE                      1061
#define IDC_NEWPASS                     1065
#define IDC_PASS1                       1068
#define IDC_OLDPASS                     1069
#define IDC_PASS2                       1070
#define IDC_MODIFY                      1071
#define IDC_DELUSER                     1073
#define ID_MANAGER                      32771
#define ID_VIEW_USERMAG                 32772
#define ID_MANAGER_ADD                  32773
#define ID_MANAGER_DEL                  32774
#define ID_MANAGER_UPDATE               32775
#define ID_MANAGER_SELECT               32776
#define ID_VIEW_SELECT                  32777
#define ID_MENUITEM32778                32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
